fx_version "adamant"
game 'gta5'
files {
	"data/**/*.meta",
	"audio/*",
    "audio/**/*",
}
client_script "data/names.lua"
data_file "CARCOLS_FILE" "data/**/carcols*.meta"
data_file "HANDLING_FILE" "data/**/handling*.meta"
data_file "VEHICLE_LAYOUTS_FILE" "data/**/vehiclelayouts*.meta"
data_file "VEHICLE_METADATA_FILE" "data/**/vehicles*.meta"
data_file "VEHICLE_VARIATION_FILE" "data/**/carvariations*.meta"
data_file "CONTENT_UNLOCKING_META_FILE" "data/**/*unlocks.meta"
data_file "AUDIO_WAVEPACK" "audio/elegyx/dlc_elegyx"
data_file "AUDIO_GAMEDATA" "audio/elegyx/elegyx_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/elegyx/elegyx_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/r34sound/dlc_r34sound"
data_file "AUDIO_GAMEDATA" "audio/r34sound/r34sound_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/r34sound/r34sound_sounds.dat"   
data_file 'AUDIO_GAMEDATA' 'audio/ta011mit4g63/ta011mit4g63_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/ta011mit4g63/ta011mit4g63_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/ta011mit4g63/dlc_ta011mit4g63'
data_file "AUDIO_GAMEDATA" "audio/ta4b11/ta4b11_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/ta4b11/ta4b11_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/ta4b11/dlc_ta4b11"
 
data_file "AUDIO_SYNTHDATA" "audio/a80ffeng/a80ffeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audio/a80ffeng/a80ffeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/a80ffeng/a80ffeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/a80ffeng/dlc_a80ffeng"
data_file "AUDIO_SYNTHDATA" "audio/b58b30/b58b30_amp.dat"
data_file "AUDIO_GAMEDATA" "audio/b58b30/b58b30_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/b58b30/b58b30_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/b58b30/dlc_b58b30"
data_file 'AUDIO_GAMEDATA' 'audio/toysupmk4/toysupmk4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/toysupmk4/toysupmk4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/toysupmk4/dlc_toysupmk4'
data_file 'AUDIO_GAMEDATA' 'audio/ea888/ea888_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/ea888/ea888_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/ea888/dlc_ea888'
data_file "AUDIO_SYNTHDATA" "audio/bmws1krreng/bmws1krreng_amp.dat"
data_file "AUDIO_GAMEDATA" "audio/bmws1krreng/bmws1krreng_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/bmws1krreng/bmws1krreng_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/bmws1krreng/dlc_bmws1krreng"
data_file 'AUDIO_GAMEDATA' 'audio/ta488f154/ta488f154_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/ta488f154/ta488f154_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/ta488f154/dlc_ta488f154'
data_file 'AUDIO_GAMEDATA' 'audio/v6audiea839/v6audiea839_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/v6audiea839/v6audiea839_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/v6audiea839/dlc_v6audiea839'
data_file 'AUDIO_GAMEDATA' 'audio/n55b30t0/n55b30t0_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/n55b30t0/n55b30t0_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/n55b30t0/dlc_n55b30t0'
data_file 'AUDIO_GAMEDATA' 'audio/aq03ej257/aq03ej257_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/aq03ej257/aq03ej257_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/aq03ej257/dlc_aq03ej257'
data_file 'AUDIO_GAMEDATA' 'audio/sentinelsg4/sentinelsg4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/sentinelsg4/sentinelsg4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/sentinelsg4/dlc_sentinelsg4'
data_file 'AUDIO_GAMEDATA' 'audio/n4g63t/n4g63t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/n4g63t/n4g63t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/n4g63t/dlc_n4g63t'
data_file 'AUDIO_SYNTHDATA' 'audio/rotary7/rotary7_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audio/rotary7/rotary7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/rotary7/rotary7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/rotary7/dlc_rotary7'
data_file "AUDIO_WAVEPACK" "audio/s15sound/dlc_s15sound"
data_file "AUDIO_GAMEDATA" "audio/s15sound/s15sound_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/s15sound/s15sound_sounds.dat"
data_file 'AUDIO_GAMEDATA' 'audio/cvpiv8/cvpiv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/cvpiv8/cvpiv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/cvpiv8/dlc_cvpiv8'
data_file 'AUDIO_GAMEDATA' 'audio/ecoboostv6/ecoboostv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/ecoboostv6/ecoboostv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/ecoboostv6/dlc_ecoboostv6'
data_file 'AUDIO_GAMEDATA' 'audio/npolchar/npolchar_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/npolchar/npolchar_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/npolchar/dlc_npolchar'
data_file 'AUDIO_GAMEDATA' 'audio/alfa690t/alfa690t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/alfa690t/alfa690t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'audio/alfa690t/dlc_alfa690t'
data_file 'AUDIO_SYNTHDATA' 'audio/bgw16/bgw16_amp.dat10'
data_file 'AUDIO_GAMEDATA' 'audio/bgw16/bgw16_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/bgw16/bgw16_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/bgw16/dlc_bgw16'
data_file 'AUDIO_GAMEDATA' 'audio/lancer/sestov10_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/lancer/sestov10_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/lancer/dlc_sestov10'
data_file 'AUDIO_GAMEDATA' 'audio/suzukigsxr1k/suzukigsxr1k_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/suzukigsxr1k/suzukigsxr1k_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/suzukigsxr1k/dlc_suzukigsxr1k'
data_file 'AUDIO_GAMEDATA' 'audio/tayamahar1/tayamahar1_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/tayamahar1/tayamahar1_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/tayamahar1/dlc_tayamahar1'
data_file 'AUDIO_GAMEDATA' 'audio/amgsound/mercm279_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/amgsound/mercm279_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/amgsound/dlc_mercm279'
data_file 'AUDIO_GAMEDATA' 'audio/chevroletlt4/chevroletlt4_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/chevroletlt4/chevroletlt4_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/chevroletlt4/dlc_chevroletlt4'
data_file 'AUDIO_GAMEDATA' 'audio/ea825/ea825_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/ea825/ea825_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/ea825/dlc_ea825'
data_file 'AUDIO_GAMEDATA' 'audio/lfasound/lfasound_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/lfasound/lfasound_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/lfasound/dlc_lfasound'
data_file 'AUDIO_GAMEDATA' 'audio/m5soundmod/m5cracklemod_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/m5soundmod/m5cracklemod_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/m5soundmod/dlc_m5cracklemod'
data_file 'AUDIO_GAMEDATA' 'audio/mercm177/mercm177_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/mercm177/mercm177_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/mercm177/dlc_mercm177'
data_file 'AUDIO_GAMEDATA' 'audio/porschema2/porschema2_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/porschema2/porschema2_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/porschema2/dlc_porschema2'
data_file 'AUDIO_GAMEDATA' 'audio/s63b44/s63b44_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/s63b44/s63b44_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/s63b44/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audio/s85b50/s85b50_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/s85b50/s85b50_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/s85b50/dlc_s85b50'
data_file 'AUDIO_GAMEDATA' 'audio/s85b50/s85b50b_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/s85b50/s85b50b_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/s85b50/dlc_s85b50b'
data_file 'AUDIO_GAMEDATA' 'audio/riot/jmbearcat_game.dat151'
data_file "AUDIO_SYNTHDATA" "audio/mbnzc63eng/mbnzc63eng_amp.dat"
data_file "AUDIO_GAMEDATA" "audio/mbnzc63eng/mbnzc63eng_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/mbnzc63eng/mbnzc63eng_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/mbnzc63eng/dlc_mbnzc63eng"
data_file "AUDIO_GAMEDATA" "audio/titan/kc23titan160polimet_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/titan/kc23titan160polimet_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/titan/dlc_kc23titan160polimet"
data_file "AUDIO_GAMEDATA" "audio/titan/kc23titan160dore_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/titan/kc23titan160dore_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/titan/dlc_kc23titan160dore"
data_file "AUDIO_GAMEDATA" "audio/titan/kc23titan160diretao_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/titan/kc23titan160diretao_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/titan/dlc_kc23titan160diretao"
data_file "AUDIO_GAMEDATA" "audio/r1200/kc12r1200gsakrapovic_game.dat"
data_file "AUDIO_SOUNDDATA" "audio/r1200/kc12r1200gsakrapovic_sounds.dat"
data_file "AUDIO_WAVEPACK" "audio/r1200/dlc_kc12r1200gsakrapovic"
data_file 'AUDIO_GAMEDATA' 'audio/trail/trail22_game.dat151'
data_file 'AUDIO_SOUNDDATA' 'audio/trail/trail22_sounds.dat54'
data_file 'AUDIO_WAVEPACK' 'audio/trail/dlc_trail22'
--{data_file 'AUDIO_SYNTHDATA' 'audio/'
--data_file 'AUDIO_GAMEDATA' 'audio/'
--data_file 'AUDIO_SOUNDDATA' 'audio/'
--data_file 'AUDIO_WAVEPACK' 'audio/'              