
-- Resources:
-- **********
-- DISCORD: https://discord.gg/4DYTf69skZ

fx_version 'cerulean'
game 'gta5'

author 'Charolis Bealmont#0001 - https://discord.gg/4DYTf69skZ'
description 'Script com sistema audio BR para NPC e sons ambiente'
version '1.0.0'

files {

  'S_MINI_SER/s_f_m_fembarber_black_mini_01.awc',
  'S_MINI_SER/s_f_m_genericcheapworker_01_latino_mini_01.awc',
  'S_MINI_SER/s_f_m_genericcheapworker_01_latino_mini_02.awc',
  'S_MINI_SER/s_f_m_genericcheapworker_01_latino_mini_03.awc',
  'S_MINI_SER/s_f_m_shop_high_white_mini_01.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_black_mini_01.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_black_mini_02.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_latino_mini_01.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_latino_mini_02.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_latino_mini_03.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_latino_mini_04.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_white_mini_01.awc',
  'S_MINI_SER/s_f_y_genericcheapworker_01_white_mini_02.awc',
  'S_MINI_SER/s_f_y_ranger_01_white_mini_01.awc',
  'S_MINI_SER/s_f_y_shop_low_white_mini_01.awc',
  'S_MINI_SER/s_f_y_shop_mid_white_mini_01.awc',
  'S_MINI_SER/s_m_m_ammucountry_white_mini_01.awc',
  'S_MINI_SER/s_m_m_autoshop_01_white_01.awc',
  'S_MINI_SER/s_m_m_ciasec_01_black_mini_01.awc',
  'S_MINI_SER/s_m_m_ciasec_01_black_mini_02.awc',
  'S_MINI_SER/s_m_m_ciasec_01_white_mini_01.awc',
  'S_MINI_SER/s_m_m_ciasec_01_white_mini_02.awc',
  'S_MINI_SER/s_m_m_fiboffice_01_black_mini_01.awc',
  'S_MINI_SER/s_m_m_fiboffice_01_black_mini_02.awc',
  'S_MINI_SER/s_m_m_fiboffice_01_latino_mini_01.awc',
  'S_MINI_SER/s_m_m_fiboffice_01_latino_mini_02.awc',
  'S_MINI_SER/s_m_m_fiboffice_01_white_mini_01.awc',
  'S_MINI_SER/s_m_m_fiboffice_01_white_mini_02.awc',
  'S_MINI_SER/s_m_m_genericcheapworker_01_latino_mini_01.awc',
  'S_MINI_SER/s_m_m_genericcheapworker_01_latino_mini_02.awc',
  'S_MINI_SER/s_m_m_genericcheapworker_01_latino_mini_03.awc',
  'S_MINI_SER/s_m_m_genericcheapworker_01_latino_mini_04.awc',
  'S_MINI_SER/s_m_m_genericmarine_01_latino_mini_01.awc',
  'S_MINI_SER/s_m_m_genericmarine_01_latino_mini_02.awc',
  'S_MINI_SER/s_m_m_genericmechanic_01_black_mini_01.awc',
  'S_MINI_SER/s_m_m_genericmechanic_01_black_mini_02.awc',
  'S_MINI_SER/s_m_m_genericpostworker_01_black_mini_01.awc',
  'S_MINI_SER/s_m_m_genericpostworker_01_black_mini_02.awc',
  'S_MINI_SER/s_m_m_genericpostworker_01_white_mini_01.awc',
  'S_MINI_SER/s_m_m_genericpostworker_01_white_mini_02.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_black_mini_01.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_black_mini_02.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_black_mini_03.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_latino_mini_01.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_latino_mini_02.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_white_mini_01.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_white_mini_02.awc',
  'S_MINI_SER/s_m_m_genericsecurity_01_white_mini_03.awc',
  'S_MINI_SER/s_m_m_hairdresser_01_black_mini_01.awc',
  'S_MINI_SER/s_m_m_paramedic_01_black_mini_01.awc',
  'S_MINI_SER/s_m_m_paramedic_01_latino_mini_01.awc',
  'S_MINI_SER/s_m_m_paramedic_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_ammucity_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_blackops_01_black_mini_01.awc',
  'S_MINI_SER/s_m_y_blackops_01_black_mini_02.awc',
  'S_MINI_SER/s_m_y_blackops_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_blackops_01_white_mini_02.awc',
  'S_MINI_SER/s_m_y_blackops_02_latino_mini_01.awc',
  'S_MINI_SER/s_m_y_blackops_02_latino_mini_02.awc',
  'S_MINI_SER/s_m_y_blackops_02_white_mini_01.awc',
  'S_MINI_SER/s_m_y_cop_01_black_mini_01.awc',
  'S_MINI_SER/s_m_y_cop_01_black_mini_02.awc',
  'S_MINI_SER/s_m_y_cop_01_black_mini_03.awc',
  'S_MINI_SER/s_m_y_cop_01_black_mini_04.awc',
  'S_MINI_SER/s_m_y_cop_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_cop_01_white_mini_02.awc',
  'S_MINI_SER/s_m_y_cop_01_white_mini_03.awc',
  'S_MINI_SER/s_m_y_cop_01_white_mini_04.awc',
  'S_MINI_SER/s_m_y_genericcheapworker_01_black_mini_01.awc',
  'S_MINI_SER/s_m_y_genericcheapworker_01_black_mini_02.awc',
  'S_MINI_SER/s_m_y_genericcheapworker_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_genericmarine_01_black_mini_01.awc',
  'S_MINI_SER/s_m_y_genericmarine_01_black_mini_02.awc',
  'S_MINI_SER/s_m_y_genericmarine_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_genericmarine_01_white_mini_02.awc',
  'S_MINI_SER/s_m_y_genericworker_01_black_mini_01.awc',
  'S_MINI_SER/s_m_y_genericworker_01_black_mini_02.awc',
  'S_MINI_SER/s_m_y_genericworker_01_latino_mini_01.awc',
  'S_MINI_SER/s_m_y_genericworker_01_latino_mini_02.awc',
  'S_MINI_SER/s_m_y_genericworker_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_genericworker_01_white_mini_02.awc',
  'S_MINI_SER/s_m_y_mcop_01_white_mini_01.awc',
  'S_MINI_SER/s_m_y_mcop_01_white_mini_02.awc',
  'S_MINI_SER/s_m_y_mcop_01_white_mini_03.awc',
  'S_MINI_SER/s_m_y_mcop_01_white_mini_04.awc',
  'S_MINI_SER/s_m_y_mcop_01_white_mini_05.awc',
  'S_MINI_SER/s_m_y_mcop_01_white_mini_06.awc',
  'S_MINI_SER/s_m_y_shop_mask_white_mini_01.awc',
  'S_MINI_SER/u_m_y_tattoo_01_white_mini_01.awc',

}


data_file 'AUDIO_WAVEPACK' 'S_MINI_SER'

