
-- Resources:
-- **********
-- DISCORD: https://discord.gg/4DYTf69skZ

fx_version 'cerulean'
game 'gta5'

author 'Charolis Bealmont#0001 - https://discord.gg/4DYTf69skZ'
description 'Script com sistema audio BR para NPC e sons ambiente'
version '1.0.0'

files {

  'ONESHOT_AMBIENCE/affluent_suburban_female_01.awc',
  'ONESHOT_AMBIENCE/affluent_suburban_female_02.awc',
  'ONESHOT_AMBIENCE/affluent_suburban_female_03.awc',
  'ONESHOT_AMBIENCE/affluent_suburban_female_04.awc',
  'ONESHOT_AMBIENCE/affluent_suburban_female_05.awc',
  'ONESHOT_AMBIENCE/affluent_suburban_female_06.awc',
  'ONESHOT_AMBIENCE/affluent_suburban_male_01.awc',
  'ONESHOT_AMBIENCE/affluent_suburban_male_02.awc',
  'ONESHOT_AMBIENCE/airport_pa_female.awc',
  'ONESHOT_AMBIENCE/airport_pa_male.awc',
  'ONESHOT_AMBIENCE/banchee_distant.awc',
  'ONESHOT_AMBIENCE/bikes_distant.awc',
  'ONESHOT_AMBIENCE/bugle_calls.awc',
  'ONESHOT_AMBIENCE/carbonizare_distant.awc',
  'ONESHOT_AMBIENCE/cheeta_distant.awc',
  'ONESHOT_AMBIENCE/commet_distant.awc',
  'ONESHOT_AMBIENCE/construction_site_male_01.awc',
  'ONESHOT_AMBIENCE/construction_site_male_02.awc',
  'ONESHOT_AMBIENCE/construction_site_male_03.awc',
  'ONESHOT_AMBIENCE/construction_site_male_04.awc',
  'ONESHOT_AMBIENCE/crows.awc',
  'ONESHOT_AMBIENCE/deamon_distant.awc',
  'ONESHOT_AMBIENCE/distant_bang.awc',
  'ONESHOT_AMBIENCE/distant_car_demo_f.awc',
  'ONESHOT_AMBIENCE/distant_car_demo_m.awc',
  'ONESHOT_AMBIENCE/distant_city_dog.awc',
  'ONESHOT_AMBIENCE/distant_containers.awc',
  'ONESHOT_AMBIENCE/distant_country_dog.awc',
  'ONESHOT_AMBIENCE/distant_countryside_bikes.awc',
  'ONESHOT_AMBIENCE/distant_forest_wolf.awc',
  'ONESHOT_AMBIENCE/distant_horns.awc',
  'ONESHOT_AMBIENCE/distant_industrial_bangs.awc',
  'ONESHOT_AMBIENCE/distant_industrial_signal.awc',
  'ONESHOT_AMBIENCE/distant_industrial_weld.awc',
  'ONESHOT_AMBIENCE/distant_prop_planes.awc',
  'ONESHOT_AMBIENCE/distant_sasquatch.awc',
  'ONESHOT_AMBIENCE/drill_instructor_megaphone.awc',
  'ONESHOT_AMBIENCE/entity_distant.awc',
  'ONESHOT_AMBIENCE/f620_distant.awc',
  'ONESHOT_AMBIENCE/feltzer_distant.awc',
  'ONESHOT_AMBIENCE/fire_background_sweeteners.awc',
  'ONESHOT_AMBIENCE/foundry_background_sweeteners.awc',
  'ONESHOT_AMBIENCE/general_ambience.awc',
  'ONESHOT_AMBIENCE/helicopter_pitching.awc',
  'ONESHOT_AMBIENCE/helicopter_rattles.awc',
  'ONESHOT_AMBIENCE/helicopter_spin_out.awc',
  'ONESHOT_AMBIENCE/janitor_walkie_talkie.awc',
  'ONESHOT_AMBIENCE/jet_plane_flyby_lrg.awc',
  'ONESHOT_AMBIENCE/jet_plane_flyby_med.awc',
  'ONESHOT_AMBIENCE/khamelion_distant.awc',
  'ONESHOT_AMBIENCE/li_female_01.awc',
  'ONESHOT_AMBIENCE/li_george_01.awc',
  'ONESHOT_AMBIENCE/li_lobby_01.awc',
  'ONESHOT_AMBIENCE/li_male_01.awc',
  'ONESHOT_AMBIENCE/li_male_02.awc',
  'ONESHOT_AMBIENCE/lightning_strike_01.awc',
  'ONESHOT_AMBIENCE/lightning_strike_02.awc',
  'ONESHOT_AMBIENCE/lightning_strike_03.awc',
  'ONESHOT_AMBIENCE/night_out_female_01.awc',
  'ONESHOT_AMBIENCE/night_out_female_02.awc',
  'ONESHOT_AMBIENCE/night_out_female_03.awc',
  'ONESHOT_AMBIENCE/night_out_female_04.awc',
  'ONESHOT_AMBIENCE/night_out_male_01.awc',
  'ONESHOT_AMBIENCE/night_out_male_02.awc',
  'ONESHOT_AMBIENCE/phq_scanner.awc',
  'ONESHOT_AMBIENCE/pier_announce_female.awc',
  'ONESHOT_AMBIENCE/pier_announce_male.awc',
  'ONESHOT_AMBIENCE/pier_foley.awc',
  'ONESHOT_AMBIENCE/player_helicopter_spin_out.awc',
  'ONESHOT_AMBIENCE/prison_tannoy.awc',
  'ONESHOT_AMBIENCE/prop_plane_flyby_duster.awc',
  'ONESHOT_AMBIENCE/prop_plane_flyby_lrg.awc',
  'ONESHOT_AMBIENCE/prop_plane_flyby_med.awc',
  'ONESHOT_AMBIENCE/prop_plane_flyby_stunt.awc',
  'ONESHOT_AMBIENCE/rapid_distant.awc',
  'ONESHOT_AMBIENCE/spooky.awc',
  'ONESHOT_AMBIENCE/stinger_distant.awc',
  'ONESHOT_AMBIENCE/subway_announcer.awc',
  'ONESHOT_AMBIENCE/test_banchee.awc',
  'ONESHOT_AMBIENCE/test_voice.awc',
  'ONESHOT_AMBIENCE/thunder_roll_01.awc',
  'ONESHOT_AMBIENCE/thunder_roll_02.awc',
  'ONESHOT_AMBIENCE/thunder_roll_03.awc',
  'ONESHOT_AMBIENCE/vacca_distant.awc',
  'ONESHOT_AMBIENCE/vb_female_01.awc',
  'ONESHOT_AMBIENCE/vb_female_02.awc',
  'ONESHOT_AMBIENCE/vb_female_03.awc',
  'ONESHOT_AMBIENCE/vb_female_04.awc',
  'ONESHOT_AMBIENCE/vb_lifeguard_01.awc',
  'ONESHOT_AMBIENCE/vb_male_01.awc',
  'ONESHOT_AMBIENCE/vb_male_02.awc',
  'ONESHOT_AMBIENCE/vb_male_03.awc',
  'ONESHOT_AMBIENCE/vultures.awc',
  
}


data_file 'AUDIO_WAVEPACK' 'ONESHOT_AMBIENCE'
