
-- Resources:
-- **********
-- DISCORD: https://discord.gg/4DYTf69skZ

fx_version 'cerulean'
game 'gta5'

author 'Charolis Bealmont#0001 - https://discord.gg/4DYTf69skZ'
description 'Script com sistema audio BR para NPC e sons ambiente'
version '1.0.0'

files {

  'S_MINI_GAN/g_f_y_ballas_01_black_mini_01.awc',
  'S_MINI_GAN/g_f_y_ballas_01_black_mini_02.awc',
  'S_MINI_GAN/g_f_y_ballas_01_black_mini_03.awc',
  'S_MINI_GAN/g_f_y_ballas_01_black_mini_04.awc',
  'S_MINI_GAN/g_f_y_families_01_black_mini_01.awc',
  'S_MINI_GAN/g_f_y_families_01_black_mini_02.awc',
  'S_MINI_GAN/g_f_y_families_01_black_mini_03.awc',
  'S_MINI_GAN/g_f_y_families_01_black_mini_04.awc',
  'S_MINI_GAN/g_f_y_families_01_black_mini_05.awc',
  'S_MINI_GAN/g_f_y_families_01_black_mini_06.awc',
  'S_MINI_GAN/g_f_y_vagos_01_latino_mini_01.awc',
  'S_MINI_GAN/g_f_y_vagos_01_latino_mini_02.awc',
  'S_MINI_GAN/g_f_y_vagos_01_latino_mini_03.awc',
  'S_MINI_GAN/g_f_y_vagos_01_latino_mini_04.awc',
  'S_MINI_GAN/g_m_m_armboss_01_white_armenian_mini_01.awc',
  'S_MINI_GAN/g_m_m_armboss_01_white_armenian_mini_02.awc',
  'S_MINI_GAN/g_m_m_armlieut_01_white_armenian_mini_01.awc',
  'S_MINI_GAN/g_m_m_armlieut_01_white_armenian_mini_02.awc',
  'S_MINI_GAN/g_m_m_chiboss_01_chinese_mini_01.awc',
  'S_MINI_GAN/g_m_m_chiboss_01_chinese_mini_02.awc',
  'S_MINI_GAN/g_m_m_chigoon_01_chinese_mini_01.awc',
  'S_MINI_GAN/g_m_m_chigoon_01_chinese_mini_02.awc',
  'S_MINI_GAN/g_m_m_chigoon_02_chinese_mini_01.awc',
  'S_MINI_GAN/g_m_m_chigoon_02_chinese_mini_02.awc',
  'S_MINI_GAN/g_m_m_korboss_01_korean_mini_01.awc',
  'S_MINI_GAN/g_m_m_korboss_01_korean_mini_02.awc',
  'S_MINI_GAN/g_m_m_mexboss_01_latino_mini_01.awc',
  'S_MINI_GAN/g_m_m_mexboss_01_latino_mini_02.awc',
  'S_MINI_GAN/g_m_m_mexboss_02_latino_mini_01.awc',
  'S_MINI_GAN/g_m_m_mexboss_02_latino_mini_02.awc',
  'S_MINI_GAN/g_m_y_armgoon_02_white_armenian_mini_01.awc',
  'S_MINI_GAN/g_m_y_armgoon_02_white_armenian_mini_02.awc',
  'S_MINI_GAN/g_m_y_ballaeast_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_ballaeast_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_ballaeast_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_ballaorig_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_ballaorig_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_ballaorig_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_ballasout_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_ballasout_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_ballasout_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_famca_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_famca_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_famca_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_famdnf_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_famdnf_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_famdnf_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_famfor_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_famfor_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_famfor_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_korean_01_korean_mini_01.awc',
  'S_MINI_GAN/g_m_y_korean_01_korean_mini_02.awc',
  'S_MINI_GAN/g_m_y_korean_02_korean_mini_01.awc',
  'S_MINI_GAN/g_m_y_korean_02_korean_mini_02.awc',
  'S_MINI_GAN/g_m_y_korlieut_01_korean_mini_01.awc',
  'S_MINI_GAN/g_m_y_korlieut_01_korean_mini_02.awc',
  'S_MINI_GAN/g_m_y_lost_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_lost_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_lost_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_lost_01_white_mini_01.awc',
  'S_MINI_GAN/g_m_y_lost_01_white_mini_02.awc',
  'S_MINI_GAN/g_m_y_lost_02_latino_mini_01.awc',
  'S_MINI_GAN/g_m_y_lost_02_latino_mini_02.awc',
  'S_MINI_GAN/g_m_y_lost_02_latino_mini_03.awc',
  'S_MINI_GAN/g_m_y_lost_02_white_mini_01.awc',
  'S_MINI_GAN/g_m_y_lost_02_white_mini_02.awc',
  'S_MINI_GAN/g_m_y_lost_03_white_mini_02.awc',
  'S_MINI_GAN/g_m_y_lost_03_white_mini_03.awc',
  'S_MINI_GAN/g_m_y_mexgoon_01_latino_mini_01.awc',
  'S_MINI_GAN/g_m_y_mexgoon_01_latino_mini_02.awc',
  'S_MINI_GAN/g_m_y_mexgoon_02_latino_mini_01.awc',
  'S_MINI_GAN/g_m_y_mexgoon_02_latino_mini_02.awc',
  'S_MINI_GAN/g_m_y_mexgoon_03_latino_mini_01.awc',
  'S_MINI_GAN/g_m_y_mexgoon_03_latino_mini_02.awc',
  'S_MINI_GAN/g_m_y_pologoon_01_latino_mini_01.awc',
  'S_MINI_GAN/g_m_y_pologoon_01_latino_mini_02.awc',
  'S_MINI_GAN/g_m_y_salvaboss_01_salvadorian_mini_01.awc',
  'S_MINI_GAN/g_m_y_salvaboss_01_salvadorian_mini_02.awc',
  'S_MINI_GAN/g_m_y_salvagoon_01_salvadorian_mini_01.awc',
  'S_MINI_GAN/g_m_y_salvagoon_01_salvadorian_mini_02.awc',
  'S_MINI_GAN/g_m_y_salvagoon_01_salvadorian_mini_03.awc',
  'S_MINI_GAN/g_m_y_salvagoon_02_salvadorian_mini_01.awc',
  'S_MINI_GAN/g_m_y_salvagoon_02_salvadorian_mini_02.awc',
  'S_MINI_GAN/g_m_y_salvagoon_02_salvadorian_mini_03.awc',
  'S_MINI_GAN/g_m_y_salvagoon_03_salvadorian_mini_01.awc',
  'S_MINI_GAN/g_m_y_salvagoon_03_salvadorian_mini_02.awc',
  'S_MINI_GAN/g_m_y_salvagoon_03_salvadorian_mini_03.awc',
  'S_MINI_GAN/g_m_y_streetpunk_01_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_streetpunk_01_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_streetpunk_01_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_streetpunk_02_black_mini_01.awc',
  'S_MINI_GAN/g_m_y_streetpunk_02_black_mini_02.awc',
  'S_MINI_GAN/g_m_y_streetpunk_02_black_mini_03.awc',
  'S_MINI_GAN/g_m_y_streetpunk02_black_mini_04.awc',

}


data_file 'AUDIO_WAVEPACK' 'S_MINI_GAN'

